# Generated by Django 3.0.8 on 2020-07-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('pk', 'title')},
        ),
    ]
